insert into documento_apresentado (nome) values ('RG');
insert into documento_apresentado (nome) values ('CPF');
insert into documento_apresentado (nome) values ('CERTIDÃO DE NASCIMENTO');
insert into documento_apresentado (nome) values ('COMPROVANTE DE ENDEREÇO');
insert into documento_apresentado (nome) values ('TITULO DE ELEITOR');
insert into documento_apresentado (nome) values ('CARTEIRA DE TRABALHO');
insert into documento_apresentado (nome) values ('CERTIDÃO DE ÓBITO');
insert into documento_apresentado (nome) values ('CERTIDÃO DE BATISMO');
insert into documento_apresentado (nome) values ('CERTIDÃO DE CASAMENTO');
insert into documento_apresentado (nome) values ('LAUDO MÉDICO');
insert into documento_apresentado (nome) values ('BOLETIM DE OCORRÊNCIA');
insert into documento_apresentado (nome) values ('CONTRA CHEQUE');
insert into documento_apresentado (nome) values ('SEGURO SAFRA');
insert into documento_apresentado (nome) values ('CD DO PA INSS');
insert into documento_apresentado (nome) values ('DECLARAÇÃO SIND RURAL');
insert into documento_apresentado (nome) values ('DECLARAÇÃO IRPF');
insert into documento_apresentado (nome) values ('SEGURO DE VIDA');
insert into documento_apresentado (nome) values ('DECLARAÇÃO DONO TERRA');
insert into documento_apresentado (nome) values ('DAP');
insert into documento_apresentado (nome) values ('CARTA DE INDEFERIMENTO');
insert into documento_apresentado (nome) values ('ESCRITURA PÚBLICA');
insert into documento_apresentado (nome) values ('CERTIDÃO CARTORÁRIA');
insert into documento_apresentado (nome) values ('FICHA FINANCEIRA');
insert into documento_apresentado (nome) values ('CRLV');
insert into documento_apresentado (nome) values ('CERTIDÃO DE ANTECEDENTES CRIMINAIS');
insert into documento_apresentado (nome) values ('PESQUISA SPC/SERASA');
insert into documento_apresentado (nome) values ('FOTOS');
insert into documento_apresentado (nome) values ('TÍTULOS DE CRÉDITOS');
insert into documento_apresentado (nome) values ('OUTROS DOCUMENTOS');